
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lang.parser;

/** CUP generated class containing symbol constants. */
public class LangParserSym {
  /* terminals */
  public static final int LBRACKET = 6;
  public static final int MULT = 17;
  public static final int TYCHAR = 36;
  public static final int CHAR_LITERAL = 28;
  public static final int DATA = 34;
  public static final int NOT = 25;
  public static final int SEMICOLON = 9;
  public static final int AND = 24;
  public static final int LT = 22;
  public static final int TYBOOL = 37;
  public static final int COMMA = 8;
  public static final int DIV = 18;
  public static final int PLUS = 15;
  public static final int IF = 39;
  public static final int DOT = 12;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int RBRACKET = 7;
  public static final int TRUE = 29;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int ATBR = 13;
  public static final int NULL = 31;
  public static final int MOD = 19;
  public static final int NEQ = 21;
  public static final int EQ = 20;
  public static final int TYID = 33;
  public static final int ITERATE = 41;
  public static final int OPEN_PARENTHESIS = 4;
  public static final int COLON = 10;
  public static final int ELSE = 40;
  public static final int LBRACE = 2;
  public static final int READ = 42;
  public static final int TYINT = 35;
  public static final int DOUBLE_COLON = 11;
  public static final int RBRACE = 3;
  public static final int CLOSE_PARENTHESIS = 5;
  public static final int FLOAT_LITERAL = 27;
  public static final int FALSE = 30;
  public static final int TYFLOAT = 38;
  public static final int GT = 23;
  public static final int SUB = 16;
  public static final int PRINT = 44;
  public static final int INT_LITERAL = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "DOUBLE_COLON",
  "DOT",
  "ATBR",
  "NEW",
  "PLUS",
  "SUB",
  "MULT",
  "DIV",
  "MOD",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "AND",
  "NOT",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "CHAR_LITERAL",
  "TRUE",
  "FALSE",
  "NULL",
  "ID",
  "TYID",
  "DATA",
  "TYINT",
  "TYCHAR",
  "TYBOOL",
  "TYFLOAT",
  "IF",
  "ELSE",
  "ITERATE",
  "READ",
  "RETURN",
  "PRINT"
  };
}

